# Generated by Django 2.2.15 on 2021-02-07 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_publico', '0002_auto_20210207_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salachatpublico',
            name='usuarios',
            field=models.ManyToManyField(help_text='usuarios conectados', to=settings.AUTH_USER_MODEL),
        ),
    ]
