# Generated by Django 2.2.15 on 2021-02-07 13:55

import cuenta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('usuario', models.CharField(max_length=30, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha registro')),
                ('ultima_conexion', models.DateTimeField(auto_now=True, verbose_name='ultima conexion')),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, default=cuenta.models.getImagenPerfilEstandar, max_length=255, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
